// ── Status Enums ─────────────────────────────
const GRIEVANCE_STATUS = {
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  CLOSED: 'CLOSED',
  REOPENED: 'REOPENED',
};

const CITIZEN_RESPONSE = {
  CONFIRMED: 'CONFIRMED',
  DISPUTED: 'DISPUTED',
  NO_RESPONSE: 'NO_RESPONSE',
  PENDING: 'PENDING',
};

const USER_ROLES = {
  CITIZEN: 'CITIZEN',
  OFFICER: 'OFFICER',
  DEPARTMENT: 'DEPARTMENT',
  COLLECTOR: 'COLLECTOR',
};

const CATEGORIES = ['ROAD', 'WATER', 'ELECTRICITY', 'SANITATION', 'HEALTH', 'EDUCATION', 'OTHER'];

// ── Thresholds ───────────────────────────────
const GPS_THRESHOLD_METERS = parseInt(process.env.GPS_THRESHOLD_METERS || '500', 10);
const EVIDENCE_TIMEOUT_HOURS = parseInt(process.env.EVIDENCE_TIMEOUT_HOURS || '24', 10);

module.exports = {
  GRIEVANCE_STATUS,
  CITIZEN_RESPONSE,
  USER_ROLES,
  CATEGORIES,
  GPS_THRESHOLD_METERS,
  EVIDENCE_TIMEOUT_HOURS,
};
